package models

type AssetType struct {
	ID                                  int               `json:"id"`
	Accountscode1                       string            `json:"accountscode1,omitempty"`
	Accountscode2                       string            `json:"accountscode2,omitempty"`
	ActiveTab                           int               `json:"active_tab"`
	AllowAllView                        bool              `json:"allow_all_view"`
	AllowallCustombuttons               bool              `json:"allowall_custombuttons"`
	AllowallStatus                      bool              `json:"allowall_status"`
	AssetDetailsTabDisplay              int               `json:"asset_details_tab_display"`
	AssetgroupId                        int               `json:"assetgroup_id"`
	AssetgroupName                      string            `json:"assetgroup_name"`
	AssettypeTab                        int               `json:"assettype_tab"`
	BusinessownerTab                    int               `json:"businessowner_tab"`
	ColumnProfileId                     int               `json:"column_profile_id,omitempty"`
	ColumnprofileoverrideName           string            `json:"columnprofileoverride_name"`
	Cost                                float64           `json:"cost,omitempty"`
	CriticalityTab                      int               `json:"criticality_tab"`
	CriticalityVisibility               int               `json:"criticality_visibility"`
	DefaultDeviceTemplate               int               `json:"default_device_template"`
	DefaultItem                         int               `json:"default_item"`
	DefaultShowinusercatalog            int               `json:"default_showinusercatalog"`
	Defaultsequence                     int               `json:"defaultsequence,omitempty"`
	DependenciesTab                     int               `json:"dependencies_tab"`
	Diagramfield1                       int               `json:"diagramfield1"`
	Diagramfield2                       int               `json:"diagramfield2"`
	Diagramfield3                       int               `json:"diagramfield3"`
	Enableresourcebooking               bool              `json:"enableresourcebooking"`
	Fields                              []AssetTypeFields `json:"fields"`
	Fiid                                int               `json:"fiid"`
	Finame                              string            `json:"finame"`
	Fiveyearlycost                      float64           `json:"fiveyearlycost"`
	Fouryearlycost                      float64           `json:"fouryearlycost"`
	Guid                                string            `json:"guid"`
	Icon                                string            `json:"icon,omitempty"`
	InventorynumberTab                  int               `json:"inventorynumber_tab"`
	IsBusinessapp                       bool              `json:"is_businessapp,omitempty"`
	IsService                           bool              `json:"is_service,omitempty"`
	ItemCode                            string            `json:"item_code"`
	Itemno                              int               `json:"itemno,omitempty"`
	Kaseyaid                            string            `json:"kaseyaid,omitempty"`
	Keyfield2Id                         int               `json:"keyfield2_id"`
	Keyfield2Name                       string            `json:"keyfield2_name"`
	Keyfield3Id                         int               `json:"keyfield3_id"`
	Keyfield3Name                       string            `json:"keyfield3_name"`
	KeyfieldId                          int               `json:"keyfield_id"`
	KeyfieldName                        string            `json:"keyfield_name"`
	LabourwarrantyendTab                int               `json:"labourwarrantyend_tab"`
	LabourwarrantystartTab              int               `json:"labourwarrantystart_tab"`
	LicenceTab                          int               `json:"licence_tab"`
	LicenceVisibility                   int               `json:"licence_visibility"`
	Linkedcontracttype                  int               `json:"linkedcontracttype"`
	Manufacturer                        int               `json:"manufacturer"`
	ManufacturerTab                     int               `json:"manufacturer_tab"`
	Memo                                string            `json:"memo,omitempty"`
	Monthlycost                         float64           `json:"monthlycost"`
	Name                                string            `json:"name"`
	NewticketPriority                   int               `json:"newticket_priority,omitempty"`
	NotesTab                            int               `json:"notes_tab"`
	NotesVisibility                     int               `json:"notes_visibility"`
	OwningbusinessappTab                int               `json:"owningbusinessapp_tab"`
	OwningciTab                         int               `json:"owningci_tab"`
	OwningportfolioTab                  int               `json:"owningportfolio_tab"`
	OwningserviceTab                    int               `json:"owningservice_tab"`
	PartswarrantyendTab                 int               `json:"partswarrantyend_tab"`
	PartswarrantystartTab               int               `json:"partswarrantystart_tab"`
	PrimaryInstanceType                 int               `json:"primary_instance_type"`
	PriorityTab                         int               `json:"priority_tab"`
	PurchasedateTab                     int               `json:"purchasedate_tab"`
	Quarterlycost                       float64           `json:"quarterlycost"`
	RefTab                              int               `json:"ref_tab"`
	ResourcebookingAllowAssetSelection  bool              `json:"resourcebooking_allow_asset_selection"`
	ResourcebookingAssetCustomField     int               `json:"resourcebooking_asset_custom_field"`
	ResourcebookingAssetRestrictionType int               `json:"resourcebooking_asset_restriction_type"`
	ResourcebookingMaxDaysAdvance       float64           `json:"resourcebooking_max_days_advance"`
	ResourcebookingMinHoursAdvance      float64           `json:"resourcebooking_min_hours_advance"`
	ResourcebookingSiteSelectionType    int               `json:"resourcebooking_site_selection_type"`
	ResourcebookingWorkdaysId           int               `json:"resourcebooking_workdays_id"`
	ServiceCategoryName                 string            `json:"service_category_name"`
	ServicesTab                         int               `json:"services_tab"`
	ShowToUsers                         bool              `json:"show_to_users"`
	SiteTab                             int               `json:"site_tab"`
	Sixmonthlycost                      float64           `json:"sixmonthlycost"`
	SlaTab                              int               `json:"sla_tab"`
	StatusTab                           int               `json:"status_tab"`
	StocklocationTab                    int               `json:"stocklocation_tab"`
	Supplier1                           int               `json:"supplier1"`
	SupplierTab                         int               `json:"supplier_tab"`
	Tagprefix                           string            `json:"tagprefix,omitempty"`
	TechnicalownerTab                   int               `json:"technicalowner_tab"`
	Threeyearlycost                     float64           `json:"threeyearlycost"`
	Twoyearlycost                       float64           `json:"twoyearlycost"`
	Use                                 int               `json:"use"`
	UserTab                             int               `json:"user_tab"`
	UserVisibility                      int               `json:"user_visibility"`
	Useteamviewer                       bool              `json:"useteamviewer"`
	VisibilityLevel                     int               `json:"visibility_level"`
	WarrantynotesTab                    int               `json:"warrantynotes_tab"`
	Weeklycost                          float64           `json:"weeklycost"`
	Yearlycost                          float64           `json:"yearlycost"`
}

type AssetTypeFields struct {
	ID         float64 `json:"id"`
	FieldId    float64 `json:"field_id"`
	FieldName  string  `json:"field_name"`
	Groupname  string  `json:"groupname,omitempty"`
	KeyfieldId string  `json:"keyfield_id,omitempty"`
	Sequence   int     `json:"sequence"`
	TabId      int     `json:"tab_id"`
	TabName    string  `json:"tab_name"`
	Techdetail int     `json:"techdetail"`
	Type       string  `json:"type"`
	TypeinfoId float64 `json:"typeinfo_id"`
	Userdetail int     `json:"userdetail"`
}
